-- MySQL Script generated by MySQL Workbench
-- Mon Feb 14 22:27:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jsf19b
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jsf19b` ;

-- -----------------------------------------------------
-- Schema jsf19b
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jsf19b` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `jsf19b` ;

-- -----------------------------------------------------
-- Table `jsf19b`.`petstore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jsf19b`.`petstore` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jsf19b`.`petstore` (
  `pst_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_name` VARCHAR(30) NOT NULL,
  `pst_street` VARCHAR(30) NOT NULL,
  `pst_city` VARCHAR(30) NOT NULL,
  `pst_state` CHAR(2) NOT NULL,
  `pst_zip` CHAR(9) NOT NULL,
  `pst_phone` BIGINT UNSIGNED NOT NULL,
  `pst_email` VARCHAR(100) NOT NULL,
  `pst_url` VARCHAR(100) NOT NULL,
  `pst_ytd_sales` DECIMAL(10,2) NOT NULL,
  `pst_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pst_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jsf19b`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jsf19b`.`customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jsf19b`.`customer` (
  `cus_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cus_fname` VARCHAR(15) NOT NULL,
  `cus_lname` VARCHAR(30) NOT NULL,
  `cus_street` VARCHAR(30) NOT NULL,
  `cus_city` VARCHAR(30) NOT NULL,
  `cus_state` CHAR(2) NOT NULL,
  `cus_zip` CHAR(9) NOT NULL,
  `cus_phone` BIGINT UNSIGNED NOT NULL,
  `cus_email` VARCHAR(100) NOT NULL,
  `cus_balance` DECIMAL(8,2) NOT NULL,
  `cus_total_sales` DECIMAL(8,2) NOT NULL,
  `cus_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`cus_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jsf19b`.`pet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jsf19b`.`pet` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jsf19b`.`pet` (
  `pet_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_id` SMALLINT UNSIGNED NOT NULL,
  `cus_id` SMALLINT UNSIGNED NULL,
  `pet_type` VARCHAR(45) NOT NULL,
  `pet_sex` ENUM('m', 'f') NOT NULL,
  `pet_cost` DECIMAL(6,2) NOT NULL,
  `pet_price` DECIMAL(6,2) NOT NULL,
  `pet_age` TINYINT NOT NULL,
  `pet_color` VARCHAR(30) NOT NULL,
  `pet_sale_date` DATE NULL,
  `pet_vaccine` ENUM('y', 'n') NOT NULL,
  `pet_neuter` ENUM('y', 'n') NOT NULL,
  `pet_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pet_id`),
  INDEX `fk_pet_customer_idx` (`cus_id` ASC) VISIBLE,
  INDEX `fk_pet_petstore1_idx` (`pst_id` ASC) VISIBLE,
  CONSTRAINT `fk_pet_customer`
    FOREIGN KEY (`cus_id`)
    REFERENCES `jsf19b`.`customer` (`cus_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pet_petstore1`
    FOREIGN KEY (`pst_id`)
    REFERENCES `jsf19b`.`petstore` (`pst_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `jsf19b`.`petstore`
-- -----------------------------------------------------
START TRANSACTION;
USE `jsf19b`;
INSERT INTO `jsf19b`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Wildwood Exotic ', '343 S 38th St', 'Springfield', 'IL', '613249843', 9194532341, 'Wildwood.exotic@aol.com', 'http://www.wildwood.exotic.com', 10000, 'notes1');
INSERT INTO `jsf19b`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Happy Paws', '93 W Atlantic Ave', 'Delray Beach', 'FL', '334539871', 6709832124, 'Happy.paws@gmail.com', 'http://www.happypawscom', 20000, 'notes2');
INSERT INTO `jsf19b`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pounce n Play', '2134 Palm Dr', 'Austin', 'TX', '750012845', 6175463287, 'Pouncenplay@hotmail.com', 'http://www.pouncenplay.com', 30000, 'notes3');
INSERT INTO `jsf19b`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Scales Exotic', '45 Pinetree Ln', 'Sacremento', 'CA', '224027362', 3549502943, 'Scales.exotic@yahoo.com', 'http://www.scalesexotic.com', 40000, 'notes4');
INSERT INTO `jsf19b`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Fly Away Feathers', '123 E Costal St', 'Wade Hampton', 'SC', '824325612', 1034756983, 'Flyawayfeathe@gmail.com', 'http://www.flyawayfeathers.com', 50000, 'notes5');
INSERT INTO `jsf19b`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Happy Friends ', '3843 S 14th St', 'Greensboro', 'NC', '938257127', 3234756983, 'Happyfriends@gmail.com', 'http://www.Happyfriends.com', 60000, 'notes6');
INSERT INTO `jsf19b`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Happy Tails', '20 N Key DR', 'Fairmount', 'WV', '681232562', 6734756983, 'Happy.tails@hotmail.com', 'http://www.happytails.com', 70000, 'notes7');
INSERT INTO `jsf19b`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pets Unleashed', '8532 Pinacle Dr', 'Montgomeroy ', 'AL', '323268474', 7934756983, 'Petsunleashed@yahoo.com', 'http://www.petsunleashed.com', 80000, 'notes8');
INSERT INTO `jsf19b`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pets Unlimited', '145 W Lincon Ave', 'Gulfport', 'MS', '213324351', 5634756983, 'Petsunlimited@aol.com', 'http://www.petsunlimited.com', 90000, 'notes9');
INSERT INTO `jsf19b`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Furry Fiesta', '87 Spanish Blvd', 'Norfolk', 'VA', '413495048', 4334756983, 'Furryfiesta@yahoo.com', 'http://www.furryfiesta.com', 15000, 'notes10');

COMMIT;


-- -----------------------------------------------------
-- Data for table `jsf19b`.`customer`
-- -----------------------------------------------------
START TRANSACTION;
USE `jsf19b`;
INSERT INTO `jsf19b`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Andy', 'Saint', '1234 Palm Dr', 'Chicago', 'IL', '600073210', 3125436547, 'Andysaint@gmail.com', 15.94, 1100.43, 'notes1');
INSERT INTO `jsf19b`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Bob', 'Evans', '32 Sky Ln', 'Birmingham', 'AL', '350058391', 2054367324, 'Bobevans@yahoo.com', 0.0, 200.54, 'notes2');
INSERT INTO `jsf19b`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Caleb', 'Duncan', '711 S 27 St', 'Dallas', 'TX', '750010194', 2149213586, 'Calebduncan@gmail.com', 231.74, 5000.21, 'notes3');
INSERT INTO `jsf19b`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Debra', 'Smith', '8680 Congress Park Dr', 'San Diego', 'CA', '224001345', 6191432593, 'Debras@hotmail.com', 382.43, 969.12, 'notes4');
INSERT INTO `jsf19b`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Esther', 'Jean', '212 Oak Terrace Dr', 'Charleston', 'WV', '253014502', 3047246291, 'e.jean12@yahoo.com', 35.21, 1923.21, 'notes5');
INSERT INTO `jsf19b`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Frank', 'Clarke', '154 Pinestead Ln', 'Florence', 'SC', '295018523', 8436482946, 'FrClarke@gmail.com', 65.32, 2193.54, 'notes6');
INSERT INTO `jsf19b`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'George', 'Lopez', '93 Sky lark Rd', 'Chapel Hill', 'NC', '275141935', 9192233453, 'geo.lo@yahoo.com', 200.52, 5432.61, 'notes7');
INSERT INTO `jsf19b`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Hank', 'Hill', '854 S 37 St', 'Richmond', 'VA', '231730256', 8049373926, 'Hankhill@aol.com', 87.63, 350.96, 'notes8');
INSERT INTO `jsf19b`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Ian', 'Wits', '44 W 85th St', 'Jackson', 'MS', '390564581', 6012128509, 'Ian.w@yahoo.com', 19.25, 4352.44, 'notes9');
INSERT INTO `jsf19b`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'James', 'Francis', '65 S 12 St', 'Lake Worth', 'FL', '334613941', 5617948156, 'jamf91@yahoo.com', 20.00, 1021.54, 'notes10');

COMMIT;


-- -----------------------------------------------------
-- Data for table `jsf19b`.`pet`
-- -----------------------------------------------------
START TRANSACTION;
USE `jsf19b`;
INSERT INTO `jsf19b`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 1, 2, 'Dobberman', 'm', 435, 585, 35, 'Black', '2010-08-12', 'y', 'y', 'notes1');
INSERT INTO `jsf19b`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 3, NULL, 'Beagal ', 'f', 500, 690, 12, 'Brown and Black', NULL, 'n', 'n', 'notes2');
INSERT INTO `jsf19b`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 4, NULL, 'Parrot', 'f', 45, 250, 45, 'Yellow and Orange', '2022-01-08', 'n', 'n', 'notes3');
INSERT INTO `jsf19b`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 2, 3, 'Lizard', 'm', 120, 1205, 93, 'Tan', NULL, 'n', 'y', 'notes4');
INSERT INTO `jsf19b`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 7, NULL, 'Frog', 'm', 50, 230, 65, 'Green', '2015-06-21', 'y', 'n', 'notes5');
INSERT INTO `jsf19b`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 9, 5, 'Bearded Dragon', 'f', 300, 960, 34, 'Brown', NULL, 'y', 'n', 'notes6');
INSERT INTO `jsf19b`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 8, 4, 'Ferret', 'f', 90, 100, 20, 'grey and White', NULL, 'y', 'y', 'notes7');
INSERT INTO `jsf19b`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 3, NULL, 'Hamster', 'f', 130, 623, 5, 'Orange and Black', '2011-02-28', 'n', 'n', 'notes8');
INSERT INTO `jsf19b`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 5, 3, 'Husky', 'm', 3500, 1500, 1, 'White and Black', NULL, 'y', 'n', 'notes9');
INSERT INTO `jsf19b`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 6, NULL, 'Bunny', 'm', 220, 540, 23, 'White', '2001-10-12', 'y', 'y', 'notes10');

COMMIT;

